### ISSUE TITLE
Please, mention GitHub Action abilities in the ReadMe

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-CI/haskell-ci#522] opened 2021-06-07 19:11 UTC
Continuation of https://github.com/haskell-CI/haskell-ci/issues/310#issuecomment-744594722
> It would be nice if the README would contain a bit of documentation on the new target, or at least mention it.

Please, label `documentation` & `PR welcome`.

Please, close #310 - that is now a misleading thread (since GitHub CI is done, I thoughts the GitHub macros/plugins/apps are a target of discussion there).

**Comment by fgaz** [comment] 2021-07-13 14:57
Duplicate of #491?

**Closed** 2021-11-29 11:12 UTC
Labels: documentation :book:, PR welcome
