### ISSUE TITLE
GHA: Checkouts are failing due to node too new for glibc

### ISSUE THREAD

**Issue by endgame** [haskell-CI/haskell-ci#738] opened 2024-07-04 22:16 UTC
The `actions/checkout@v3` of a generated GHA workflow fails with:
```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```
This is because of https://github.com/actions/checkout/issues/1809, which updated the node version used by the checkout action. The generated workflows are still using `ubuntu-20.04`.

It might be time to upgrade the runners to at least `ubuntu-22.04` and possibly also use a newer version of the `buildpack-deps` container? (it's currently on `bionic`, i.e., 18.04)

**Comment by endgame** [comment] 2024-07-04 23:16
I have manually updated a test workflow to use an `ubuntu-22.04` runner (which did nothing but should happen anyway) and changed the container to `buildpack-deps:jammy` (which did make the `checkout` step run successfully).

The workflow in question is currently private but did successfully complete for GHCs 8.10.7, 9.0.2, 9.2.4, 9.4.5, 9.6.4, and 9.8.2, so I think it's a safe change.

**Comment by phadej** [comment] 2024-07-05 08:43
> buildpack-deps:jammy 

The default distribution (i.e. container) used is *jammy* (i.e. container) https://github.com/haskell-CI/haskell-ci/blob/d6898d90d0809bede0d82c70449f566eb00809e7/src/HaskellCI/Config/History.hs#L19. I'm confused, what is happening. Please link to a reproducer (commit and GHA run).

**Comment by hasufell** [comment] 2024-07-05 10:43
GitHub is incompetent. All docker images that use a glibc older than 2.27 are now broken.

**Comment by phadej** [comment] 2024-07-05 10:59
Glibc 2.28 was released on 1 Aug 2018. For a freely available service, I wouldn't complain too much.

**Comment by hasufell** [comment] 2024-07-05 11:08
> Glibc 2.28 was released on 1 Aug 2018. For a freely available service, I wouldn't complain too much. Upgrade and move on.

Upgrade end users systems? Aha.

**Comment by phadej** [comment] 2024-07-05 11:09
@hasufell 

e.g. ubuntu focal (20.04) comes with glibc-2.31. and Ubuntu-18.04 end of support was a year ago, in June 2023. If you use Ubuntu-18.04, then yes, I'd say you should upgrade.

So I don't know what is the issue OP has.  `haskell-ci` uses checkout@v4 for few months already, so they are not using the recent version.

**Comment by hasufell** [comment] 2024-07-05 11:10
> e.g. ubuntu focal (20.04) comes with glibc-2.31. and Ubuntu-18.04 end of support was a year ago, in June 2023. If you use Ubuntu-18.04, then yes, I'd say you should upgrade.

Both 18.04 and 16.04 are under "Extended Security Maintenance", so they're still supported.

**Comment by endgame** [comment] 2024-07-05 14:09
> > buildpack-deps:jammy
> 
> The default distribution (i.e. container) used is _jammy_ (i.e. container)
> 
> https://github.com/haskell-CI/haskell-ci/blob/d6898d90d0809bede0d82c70449f566eb00809e7/src/HaskellCI/Config/History.hs#L19
> . I'm confused, what is happening. Please link to a reproducer (commit and GHA run).

The latest version on Hackage (0.18.1) doesn't include this file, and indeed uses an old distribution by default:

```
(using the 0.18.1 sdist from Hackage)
[~/haskell-ci-0.18.1]$ cabal run haskell-ci -- dump-config | grep distribution
-- distribution version (xenial, bionic, focal, jammy)
distribution: bionic
```

So if HEAD already has a fix for this, then the change to the distribution name in #739 is wrong and all that's needed is a new Hackage release? I can rebase that to only change the runner ubuntu version, if you want to change that before the next version goes to Hackage. But it seems that the latest Hackage release is generating broken configs, so it probably warrants a new release soon.

**Comment by sgraf812** [comment] 2024-07-12 16:29
Confirming that the CI workflow generated for `happy` is affected as well, even if re-generated with the most recent released version 0.18.1.

**Comment by phadej** [comment] 2024-07-12 16:31
Issue is fixed in master. There is no ETA for Hackage release.

**Closed by phadej** 2024-07-12 16:31 UTC

**Comment by endgame** [comment] 2024-07-12 21:53
That means the latest public release of `haskell-ci` is generating broken configurations by default, and there's no ETA for when that will be remedied. For anyone else visiting this issue, try overriding the container distribution by creating `cabal.haskell-ci` with the following contents, and running `haskell-ci regenerate`:
```
distribution: jammy
```

**Comment by lf-** [comment] 2025-01-31 21:55
> That means the latest public release of `haskell-ci` is generating broken configurations by default, and there's no ETA for when that will be remedied. For anyone else visiting this issue, try overriding the container distribution by creating `cabal.haskell-ci` with the following contents, and running `haskell-ci regenerate`:
> 
> ```
> distribution: jammy
> ```

I think this possibly shouldn't work, since 0.18.1 at least only uses this for buildpack-deps, *not* the runs-on field (which apparently regressed from 22.04 to 20.04 since someone last ran haskell-ci 0.15.20230115 in early 2023? Confused). Going to try it anyway, thanks for the suggestion!
