### ISSUE TITLE
GHA Consider upload package candidates to hackage using github actions 

### ISSUE THREAD

**Issue by jneira** [haskell-CI/haskell-ci#467] opened 2021-01-11 11:11 UTC
* This is correlated with #36 (upload packages to hackage using travis)
  * As discussed there, it is safer to upload only candidates
* Afaik there is no github action to do it (if anybody knows there is one in the wild please link it!)
  * So as first step we should create a github action to do it
* Ideally it should support multipackage project layouts (like haskell-language-server :slightly_smiling_face: )
* It could be triggered by git tags or using a convention in the git commit message

**Comment by phadej** [comment] 2021-01-11 11:16
At the moment this is not actionable issue. As I don't need this feature (and won't use it), i'm tempted to close this issue until someone clearly promises (and starts) to work on it. (I'm also sceptical of the usefulness).

Storiging sdists as artifacts could be useful though.

**Comment by jneira** [comment] 2021-01-11 11:28
Thanks for the feedback.

> I'm also sceptical of the usefulness

Well, we are about to upload up to 11 packages from hls and it supposes quite maintaners work, so automate the more possible can help to agilize the development process.

> As I don't need this feature (and won't use it), i'm tempted to close this issue until someone clearly promises (and starts) to work on it.

I can't promise nothing but i want try to create that github action (that can be used directly in our repo of course). No experience about creating github actions so not sure if i will be able to finish. :worried: 
So feel free to close it, no problem, only wanted to know if anybody could find useful such feature and/or had started to work in something similar.

**Comment by phadej** [comment] 2021-01-11 11:33
> Well, we are about to upload up to 11 packages from hls and it supposes quite maintaners work, so automate the more possible can help to agilize the development process.

What is wrong with having a single repository and

```
git clean -fdx
cabal sdist all
cabal upload dist-newstyle/sdist/*.tar.gz
```

**Closed by phadej** 2021-01-11 11:33 UTC

**Comment by jneira** [comment] 2021-01-11 11:45
Thanks for the suggestion, i would like to run a `cabal check` (that cant take any target afaik, you have to cd into each subpackage) and `cabal haddock` before to check everything is ok (maybe i am overlooking it?). And only upload packages that effectively have changed and we want to upload explicitly (i suppose cabal upload will fail if there is a previous package uploaded with the same version?)

**Comment by phadej** [comment] 2021-01-11 11:51
you can `cabal haddock all` or particular targets.

I also opened an https://github.com/haskell/cabal/issues/7242 (I thought I did that, but couldn't find old issue). The problem is that currently `check` functionality wants to change workdir etc, so there is some refactoring to be done, so it's not a mess when generalized. Something which could be in `cabal-install-3.6` though.

**Comment by jneira** [comment] 2021-01-11 12:10
Thanks for opening the issue.
Only want to mention that there exists already a github action to upload to hackage (even definitely): https://github.com/haskell-actions/hackage-publish
